name: worldsmith_studio
version: 0.0.0+1
description: Create RPGs with no code.
publish_to: "none"

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dart_synthizer: ^0.7.7
  file_picker: ^4.3.3
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  path: ^1.8.1
  shared_preferences: ^2.0.13
  short_uuids: ^2.0.0
  url_launcher: ^6.0.20
  worldsmith: ^0.7.0
  ziggurat: ^0.33.0
  ziggurat_sounds: ^0.13.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
flutter:
  uses-material-design: true
