name: worldsmith_studio
version: 0.0.8
description: Create RPGs with no code.
publish_to: "none"

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dart_sdl: ^0.9.3
  dart_synthizer: ^0.7.8
  dio: ^4.0.4
  file_picker: ^4.5.0
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  intl: ^0.17.0
  json_annotation: ^4.4.0
  path: ^1.8.0
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  short_uuids: ^2.0.0
  url_launcher: ^6.0.20
  worldsmith:
    path: ../worldsmith
  ziggurat: ^0.42.1
  ziggurat_sounds: ^0.22.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
flutter:
  uses-material-design: true
